---
apiVersion: "v1"
kind: Pod
metadata:
  name: whoareyou
  labels:
    app: whoareyou
spec:
  restartPolicy: Always
  containers:
  - image: "asia.gcr.io/microservicesbook-123/whoareyou"
    name: whoareyou
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    env:
    - name: SERVICE_NAME
      value: "whoareyou"
    - name: ADDR
      value: ":8080"

